import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';

const pJS = Plus_Jakarta_Sans({
    subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
          <body className={`${pJS.className} antialiased`}>
              <ThemeProvider
                  attribute={'class'}
                  defaultTheme="light"
                  enableSystem={false}
                  disableTransitionOnChange
              >
                  {children}
              </ThemeProvider>
          </body>
      </html>
  );
}
