import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Providers from './providers';
import { Toaster } from 'react-hot-toast';

const font = Geist({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Habitz',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${font.className} antialiased`}>
                <ThemeProvider
                    attribute={'class'}
                    defaultTheme="light"
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <Providers>
                        {children}
                        <Toaster
                            toastOptions={{
                                style: {
                                    fontSize: '13px',
                                    background: '#171717',
                                    color: '#fff',
                                    borderRadius: '50px',
                                },
                            }}
                        />
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    );
}
